spring:
  application.name: spring-security-demo
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/proselyte/protocol/openid-connect/certs
jwt:

