spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username:
    password:
  liquibase:
    enabled: false
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host:port/realms/realmName/protocol/openid-connect/certs


eureka:
  client:
    enabled: false

keycloak:
  realm: realmId
  server-url: http://host:port
  user-sync-client:
    client-id: clientId
    client-secret: clientSecret